# -*- coding: utf-8 -*-
"""Species_matrix_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILeRcTsQU2IN0vDj4fSzQ9yxdgOX1o1o
"""
import pandas as pd
import re

# Load TSV file
df = pd.read_csv("/content/gtdb_arch_with_species.tsv", sep="\t")

def relabel_species(tax):
    if pd.isna(tax):
        return "Unknown"

    # Find genus
    genus_match = re.search(r"g__([^;]+)", tax)
    species_match = re.search(r"s__([^;]*)$", tax)

    # Handle missing genus
    if not genus_match:
        return "Unknown"

    genus = genus_match.group(1).strip()

    # If species is missing or blank → Genus spp.
    if not species_match:
        return f"{genus} spp."

    species = species_match.group(1).strip()

    if species == "":
        return f"{genus} spp."
    else:
        return species

# Apply the relabeling function
df["Relabeled_Species"] = df["Species"].apply(relabel_species)

# Save output
df.to_csv("gtdb_arch_with_species_relabelled.tsv", sep="\t", index=False)

print("Finished! Saved as gtdb_arch_with_species_relabelled.tsv")

# --- STEP 1: Load the file properly ---
import pandas as pd

# Read as tab-delimited (not CSV with commas!)
df = pd.read_csv("/content/gtdb_with_species_relabelled.tsv", sep="\t")

# Inspect
print(df.head())
print(df.shape)

# --- STEP 2: Pivot to species × samples matrix ---
# Rows = species, Columns = samples, Values = TPM
tpm_matrix = df.pivot_table(
    index="Taxon",
    columns="Sample_ID",
    values="TPM",
    aggfunc="mean"  # in case duplicates exist
)

# --- STEP 3: Save clean TPM matrix for R/limma ---
tpm_matrix.to_csv("TPM_matrix.csv")   # CSV format
tpm_matrix.to_csv("TPM_matrix.tsv", sep="\t")  # TSV (easier for R)

print(" TPM matrix saved! Shape:", tpm_matrix.shape)
