# -*- coding: utf-8 -*-
"""Minimal_code_demonstration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1asr4YhT_Ctb5htnDhC1Eneh8BpykpsrO
"""

!pip install econml

# ==========================================================
# Minimal Causal Demonstration with Robustness Extensions
# Fusobacterium nucleatum → CRC
# Includes:
#   - Double Machine Learning
#   - Bootstrap CI + distributions
#   - Negative Control Taxon
#   - Forest Plot Comparison
#   - Sensitivity (E-value)
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.utils import resample
from econml.dml import LinearDML

# ----------------------------------------------------------
# 1. Load and Align Data (NO TRANSPOSE)
# ----------------------------------------------------------

microbiome = pd.read_csv("CRC_species_data.csv", index_col=0)
metadata = pd.read_csv("/content/CRC_metadata.csv", index_col=0)

# Clean sample IDs
microbiome.index = microbiome.index.astype(str).str.strip()
metadata.index = metadata.index.astype(str).str.strip()

# Match samples
common_sample_ids = microbiome.index.intersection(metadata.index)

if len(common_sample_ids) == 0:
    raise ValueError("No matching sample IDs between microbiome and metadata.")

microbiome = microbiome.loc[common_sample_ids]
metadata = metadata.loc[common_sample_ids]

data = metadata.join(microbiome)

print("Final merged shape:", data.shape)

# ----------------------------------------------------------
# 2. Define Outcome, Confounders, Taxa
# ----------------------------------------------------------

outcome = "Group"
confounders = ["Age", "BMI", "Sex"]

# Binary outcome
data["Cancer_binary"] = (data[outcome] == "Cancer").astype(int)

# Encode Sex if needed
if data["Sex"].dtype == "object":
    data["Sex"] = data["Sex"].map({"Male": 1, "Female": 0})

# Check confounders exist
missing_conf = [c for c in confounders if c not in data.columns]
if len(missing_conf) > 0:
    raise ValueError(f"Missing confounders: {missing_conf}")

# Detect Fusobacterium nucleatum
fus_cols = [c for c in data.columns if "Fusobacterium" in c and "nucleatum" in c]
if len(fus_cols) == 0:
    raise ValueError("Fusobacterium nucleatum not found.")

fus_taxon = fus_cols[0]

# Negative control: Acidaminococcus intestini
neg_cols = [c for c in data.columns if "Acidaminococcus intestini" in c]
if len(neg_cols) == 0:
    raise ValueError("Negative control taxon not found.")

neg_taxon = neg_cols[0]

print("Exposure taxon:", fus_taxon)
print("Negative control taxon:", neg_taxon)

analysis_cols = [fus_taxon, neg_taxon, "Cancer_binary"] + confounders
data = data[analysis_cols].dropna()

print("Final analysis sample size:", len(data))

# ----------------------------------------------------------
# 3. DML Function
# ----------------------------------------------------------

def run_dml(exposure_col, dataset):

    Y = dataset["Cancer_binary"].values
    T = dataset[exposure_col].values
    X = dataset[confounders].values

    model_y = RandomForestRegressor(
        n_estimators=200,
        min_samples_leaf=10,
        random_state=42
    )

    model_t = RandomForestRegressor(
        n_estimators=200,
        min_samples_leaf=10,
        random_state=42
    )

    dml = LinearDML(
        model_y=model_y,
        model_t=model_t,
        discrete_treatment=False,
        cv=5,
        random_state=42
    )

    dml.fit(Y, T, X=X)

    ate = float(dml.ate(X=X))
    ci_low, ci_high = dml.ate_interval(X=X)

    return ate, ci_low, ci_high

# ----------------------------------------------------------
# 4. Bootstrap Function
# ----------------------------------------------------------

def bootstrap_ate(exposure_col, dataset, n_boot=300):

    ates = []

    for i in range(n_boot):
        boot_sample = resample(dataset, replace=True, n_samples=len(dataset))
        ate, _, _ = run_dml(exposure_col, boot_sample)
        ates.append(ate)

    ates = np.array(ates)

    mean_ate = np.mean(ates)
    lower = np.percentile(ates, 2.5)
    upper = np.percentile(ates, 97.5)

    return mean_ate, lower, upper, ates

# ----------------------------------------------------------
# 5. Run Analyses
# ----------------------------------------------------------

# Asymptotic DML
fus_ate, fus_ci_low, fus_ci_high = run_dml(fus_taxon, data)
neg_ate, neg_ci_low, neg_ci_high = run_dml(neg_taxon, data)

# Bootstrap
fus_boot_mean, fus_boot_low, fus_boot_high, fus_boot_dist = bootstrap_ate(fus_taxon, data)
neg_boot_mean, neg_boot_low, neg_boot_high, neg_boot_dist = bootstrap_ate(neg_taxon, data)

print("\n===== ASYMPTOTIC DML =====")
print("F. nucleatum:", fus_ate, (fus_ci_low, fus_ci_high))
print("Negative control:", neg_ate, (neg_ci_low, neg_ci_high))

print("\n===== BOOTSTRAP =====")
print("F. nucleatum:", fus_boot_mean, (fus_boot_low, fus_boot_high))
print("Negative control:", neg_boot_mean, (neg_boot_low, neg_boot_high))

# ----------------------------------------------------------
# 6. Sensitivity (E-value for F. nucleatum)
# ----------------------------------------------------------

odds_ratio = np.exp(fus_ate)

def compute_e_value(or_est):
    if or_est <= 1:
        or_est = 1 / or_est
    return or_est + np.sqrt(or_est * (or_est - 1))

e_value = compute_e_value(odds_ratio)

print("\nApproximate OR (F. nucleatum):", odds_ratio)
print("E-value:", e_value)

# ----------------------------------------------------------
# 7. Forest Plot (Bootstrap CI)
# ----------------------------------------------------------

plt.figure(figsize=(7,3))

plt.errorbar(
    fus_boot_mean, 1,
    xerr=[[fus_boot_mean - fus_boot_low],
          [fus_boot_high - fus_boot_mean]],
    fmt='o'
)

plt.errorbar(
    neg_boot_mean, 0,
    xerr=[[neg_boot_mean - neg_boot_low],
          [neg_boot_high - neg_boot_mean]],
    fmt='o'
)

plt.axvline(x=0)
plt.yticks(
    [0,1],
    ["Acidaminococcus intestini (Negative Control)",
     "F. nucleatum"]
)

plt.xlabel("Bootstrap Average Treatment Effect (ATE)")
plt.title("Causal Effect with Negative Control")
plt.tight_layout()
plt.savefig("Forest_with_Negative_Control.png", dpi=300)
plt.show()

# ----------------------------------------------------------
# 8. Bootstrap Distribution Plots
# ----------------------------------------------------------

plt.figure(figsize=(10,4))

# F. nucleatum
plt.subplot(1,2,1)
plt.hist(fus_boot_dist, bins=30, density=True)
plt.axvline(0)
plt.axvline(fus_boot_mean)
plt.title("Bootstrap Distribution\nF. nucleatum")
plt.xlabel("ATE")
plt.ylabel("Density")

# Negative control
plt.subplot(1,2,2)
plt.hist(neg_boot_dist, bins=30, density=True)
plt.axvline(0)
plt.axvline(neg_boot_mean)
plt.title("Bootstrap Distribution\nNegative Control")
plt.xlabel("ATE")

plt.tight_layout()
plt.savefig("Bootstrap_Distributions.png", dpi=300)
plt.show()

# ----------------------------------------------------------
# 9. Save Results
# ----------------------------------------------------------

results = pd.DataFrame({
    "Taxon": [fus_taxon, neg_taxon],
    "ATE_asymptotic": [fus_ate, neg_ate],
    "CI_lower_asymptotic": [fus_ci_low, neg_ci_low],
    "CI_upper_asymptotic": [fus_ci_high, neg_ci_high],
    "ATE_bootstrap_mean": [fus_boot_mean, neg_boot_mean],
    "CI_lower_bootstrap": [fus_boot_low, neg_boot_low],
    "CI_upper_bootstrap": [fus_boot_high, neg_boot_high]
})

results.to_csv("DML_bootstrap_negative_control_results.csv", index=False)

print("\nAll results saved successfully.")

# ----------------------------------------------------------
# 10. Per-Project (Cohort) Analysis
# ----------------------------------------------------------

print("\n===== PER-PROJECT ANALYSIS =====")

project_results = []

for project_name in data["Project"].unique():

    project_data = data[data["Project"] == project_name]

    # Skip very small cohorts
    if len(project_data) < 50:
        continue

    mean_ate, low, high, _ = bootstrap_ate(
        fus_taxon,
        project_data,
        n_boot=100
    )

    project_results.append({
        "Project": project_name,
        "N": len(project_data),
        "ATE_bootstrap_mean": mean_ate,
        "CI_lower": low,
        "CI_upper": high
    })

    print(project_name, "N=", len(project_data),
          "ATE=", mean_ate, "CI=", (low, high))

project_df = pd.DataFrame(project_results)

# ----------------------------------------------------------
# Per-Project Forest Plot
# ----------------------------------------------------------

plt.figure(figsize=(7, len(project_df)*0.6))

for i, row in project_df.iterrows():
    plt.errorbar(
        row["ATE_bootstrap_mean"],
        i,
        xerr=[[row["ATE_bootstrap_mean"] - row["CI_lower"]],
              [row["CI_upper"] - row["ATE_bootstrap_mean"]]],
        fmt='o'
    )

plt.axvline(x=0)
plt.yticks(range(len(project_df)), project_df["Project"])
plt.xlabel("Bootstrap ATE (F. nucleatum)")
plt.title("Per-Project Effect Estimates (100 Bootstrap)")
plt.tight_layout()
plt.savefig("Per_Project_Forest.png", dpi=300)
plt.show()

# Save cohort results
project_df.to_csv("Per_Project_DML_Results.csv", index=False)

print("\nPer-project analysis completed.")